# Generated by Django 6.0.2 on 2026-03-02 17:27

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Subject',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=200)),
                ('category', models.CharField(choices=[('core', 'Core & Practical'), ('theory', 'Theoretical Foundations'), ('allied', 'Allied & Supporting')], max_length=20)),
            ],
        ),
    ]
