# Generated by Django 6.0.2 on 2026-03-03 15:53

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('learning', '0002_subject_description'),
    ]

    operations = [
        migrations.AlterField(
            model_name='subject',
            name='category',
            field=models.CharField(choices=[('core', 'Core & Practical'), ('theory', 'Theoretical Foundations'), ('allied', 'Allied & Supporting'), ('emerging', 'Emerging Technologies & Professional Skills')], max_length=20),
        ),
    ]
