# Generated by Django 6.0.2 on 2026-03-03 17:47

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('learning', '0003_alter_subject_category'),
    ]

    operations = [
        migrations.AddField(
            model_name='subject',
            name='course_link',
            field=models.URLField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='subject',
            name='youtube_link',
            field=models.URLField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='subject',
            name='category',
            field=models.CharField(choices=[('core', 'Core & Practical'), ('theory', 'Theoretical Foundations'), ('allied', 'Allied & Supporting'), ('emerging', 'Emerging Skills')], max_length=20),
        ),
    ]
