# Generated by Django 6.0.2 on 2026-03-04 18:34

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('learning', '0004_subject_course_link_subject_youtube_link_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='subject',
            name='thumbnail',
            field=models.ImageField(blank=True, null=True, upload_to='thumbnails/'),
        ),
    ]
