# Generated by Django 6.0.2 on 2026-03-06 15:25

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('learning', '0006_quiz'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='quiz',
            name='correct_option',
        ),
        migrations.AddField(
            model_name='quiz',
            name='correct_answer',
            field=models.CharField(default='A', max_length=200),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='quiz',
            name='question',
            field=models.CharField(max_length=500),
        ),
    ]
