# Generated by Django 6.0.2 on 2026-03-07 20:30

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('learning', '0007_remove_quiz_correct_option_quiz_correct_answer_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='quiz',
            name='option1',
            field=models.CharField(max_length=2000),
        ),
        migrations.AlterField(
            model_name='quiz',
            name='option2',
            field=models.CharField(max_length=2000),
        ),
        migrations.AlterField(
            model_name='quiz',
            name='option3',
            field=models.CharField(max_length=2000),
        ),
        migrations.AlterField(
            model_name='quiz',
            name='option4',
            field=models.CharField(max_length=2000),
        ),
        migrations.AlterField(
            model_name='quiz',
            name='question',
            field=models.CharField(max_length=5000),
        ),
    ]
